# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 06:36
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, verbose_name='Keterangan Tambahan')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Waktu diedit')),
                ('status', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_delete', models.BooleanField(default=False, verbose_name='Soft Delete')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nama Kendaraan')),
                ('driver', models.CharField(max_length=50, verbose_name='Pengemudi')),
                ('number', models.CharField(max_length=10, verbose_name='Nomer Kendaraan')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasitas')),
            ],
        ),
    ]
