# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Nama Angkutan')),
                ('driver', models.CharField(max_length=50, verbose_name='Pengemudi')),
                ('number', models.CharField(max_length=50, verbose_name='Nomer Angkutan')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasitas')),
            ],
        ),
    ]
